cusp: cusp::default_monitor< Real > Class Template Reference
cusp::default_monitor< Real > Class Template Reference
[Monitors]
#include <monitor.h>
Public Member Functions
template<typename Vector >
default_monitor (const Vector &b, size_t iteration_limit=500, Real relative_tolerance=1e-5, Real absolute_tolerance=0)
void operator++ (void)
template<typename Vector >
bool finished (const Vector &r)
bool converged () const
Real residual_norm () const
size_t iteration_count () const
size_t iteration_limit () const
Real relative_tolerance () const
Real absolute_tolerance () const
Real tolerance () const
Protected Attributes
Real r_norm
Real b_norm
Real relative_tolerance_
Real absolute_tolerance_
size_t iteration_limit_
size_t iteration_count_
Detailed Description
template<typename Real>
class cusp::default_monitor< Real >
default_monitor : Implements standard convergence criteria and reporting for iterative solvers.
Template Parameters:
Real real-valued type (e.g. float or double).
The following code snippet demonstrates how to configure the default_monitor and use it with an iterative solver.
  #include <cusp/csr_matrix.h>
  #include <cusp/monitor.h>
  #include <cusp/krylov/cg.h>
  #include <cusp/gallery/poisson.h>
  int main(void)
  {
      // create an empty sparse matrix structure (CSR format)
      cusp::csr_matrix<int, float, cusp::device_memory> A;
      // initialize matrix
      cusp::gallery::poisson5pt(A, 10, 10);
      // allocate storage for solution (x) and right hand side (b)
      cusp::array1d<float, cusp::device_memory> x(A.num_rows, 0);
      cusp::array1d<float, cusp::device_memory> b(A.num_rows, 1);
      // set stopping criteria:
      //  iteration_limit    = 100
      //  relative_tolerance = 1e-6
      cusp::default_monitor<float> monitor(b, 100, 1e-6);
      // solve the linear system A x = b
      cusp::krylov::cg(A, x, b, monitor);
      // report solver results
      if (monitor.converged())
      {
          std::cout << "Solver converged to " << monitor.relative_tolerance() << " relative tolerance";
          std::cout << " after " << monitor.iteration_count() << " iterations" << std::endl;
      }
      else
      {
          std::cout << "Solver reached iteration limit " << monitor.iteration_limit() << " before converging";
          std::cout << " to " << monitor.relative_tolerance() << " relative tolerance " << std::endl;
      }
      return 0;
  }
See also:
verbose_monitor
Constructor & Destructor Documentation
template<typename Real> template<typename Vector > cusp::default_monitor< Real >::default_monitor (const Vector & b, size_t iteration_limit = 500, Real relative_tolerance = 1e-5, Real absolute_tolerance = 0) [inline]
Construct a default_monitor for a given right-hand-side b
The default_monitor terminates iteration when the residual norm satisfies the condition ||b - A x|| <= absolute_tolerance + relative_tolerance * ||b|| or when the iteration limit is reached.
Parameters:
b right-hand-side of the linear system A x = b
iteration_limit maximum number of solver iterations to allow
relative_tolerance determines convergence criteria
absolute_tolerance determines convergence criteria
Template Parameters:
VectorType vector
Member Function Documentation
template<typename Real> Real cusp::default_monitor< Real >::absolute_tolerance () const [inline]
absolute tolerance
Referenced by cusp::default_monitor< Real >::tolerance().
template<typename Real> bool cusp::default_monitor< Real >::converged () const [inline]
whether the last tested residual satifies the convergence tolerance
References cusp::default_monitor< Real >::residual_norm(), and cusp::default_monitor< Real >::tolerance().
Referenced by cusp::convergence_monitor< Real >::finished(), cusp::verbose_monitor< Real >::finished(), and cusp::default_monitor< Real >::finished().
template<typename Real> template<typename Vector > bool cusp::default_monitor< Real >::finished (const Vector & r) [inline]
applies convergence criteria to determine whether iteration is finished
Parameters:
r residual vector of the linear system (r = b - A x)
Template Parameters:
Vector vector
Reimplemented in cusp::verbose_monitor< Real >, and cusp::convergence_monitor< Real >.
References cusp::default_monitor< Real >::converged(), cusp::default_monitor< Real >::iteration_count(), and cusp::default_monitor< Real >::iteration_limit().
template<typename Real> size_t cusp::default_monitor< Real >::iteration_count () const [inline]
number of iterations
Referenced by cusp::convergence_monitor< Real >::finished(), cusp::verbose_monitor< Real >::finished(), and cusp::default_monitor< Real >::finished().
template<typename Real> size_t cusp::default_monitor< Real >::iteration_limit () const [inline]
maximum number of iterations
Referenced by cusp::convergence_monitor< Real >::finished(), cusp::verbose_monitor< Real >::finished(), cusp::default_monitor< Real >::finished(), and cusp::verbose_monitor< Real >::verbose_monitor().
template<typename Real> void cusp::default_monitor< Real >::operator++ (void) [inline]
increment the iteration count
template<typename Real> Real cusp::default_monitor< Real >::relative_tolerance () const [inline]
relative tolerance
Referenced by cusp::default_monitor< Real >::tolerance().
template<typename Real> Real cusp::default_monitor< Real >::residual_norm () const [inline]
Euclidean norm of last residual
Referenced by cusp::default_monitor< Real >::converged(), and cusp::verbose_monitor< Real >::finished().
template<typename Real> Real cusp::default_monitor< Real >::tolerance () const [inline]
tolerance
Equal to absolute_tolerance() + relative_tolerance() * ||b||
References cusp::default_monitor< Real >::absolute_tolerance(), and cusp::default_monitor< Real >::relative_tolerance().
Referenced by cusp::default_monitor< Real >::converged(), and cusp::verbose_monitor< Real >::verbose_monitor().
The documentation for this class was generated from the following file:
monitor.h