cusp: cusp::ell_matrix< IndexType, ValueType, MemorySpace > Class Template Reference
cusp::ell_matrix< IndexType, ValueType, MemorySpace > Class Template Reference
[Sparse Matrix Containers]
#include <ell_matrix.h>
Classes
struct rebind
Public Types
typedef cusp::array2d
< IndexType, MemorySpace,
cusp::column_major > column_indices_array_type
typedef cusp::array2d
< ValueType, MemorySpace,
cusp::column_major > values_array_type
typedef cusp::ell_matrix
< IndexType, ValueType,
MemorySpace > container
typedef cusp::ell_matrix_view
< typename
column_indices_array_type::view,
typename
values_array_type::view,
IndexType, ValueType,
MemorySpace > view
typedef cusp::ell_matrix_view
< typename
column_indices_array_type::const_view,
typename
values_array_type::const_view,
IndexType, ValueType,
MemorySpace > const_view
Public Member Functions
ell_matrix ()
ell_matrix (size_t num_rows, size_t num_cols, size_t num_entries, size_t num_entries_per_row, size_t alignment=32)
template<typename MatrixType >
ell_matrix (const MatrixType &matrix)
void resize (size_t num_rows, size_t num_cols, size_t num_entries, size_t num_entries_per_row)
void resize (size_t num_rows, size_t num_cols, size_t num_entries, size_t num_entries_per_row, size_t alignment)
void swap (ell_matrix &matrix)
template<typename MatrixType >
ell_matrix & operator= (const MatrixType &matrix)
Public Attributes
column_indices_array_type column_indices
values_array_type values
Static Public Attributes
static const IndexType invalid_index = static_cast<IndexType>(-1)
Detailed Description
template<typename IndexType, typename ValueType, class MemorySpace>
class cusp::ell_matrix< IndexType, ValueType, MemorySpace >
ell_matrix : ELLPACK/ITPACK matrix container
Template Parameters:
IndexType Type used for matrix indices (e.g. int).
ValueType Type used for matrix values (e.g. float).
MemorySpace A memory space (e.g. cusp::host_memory or cusp::device_memory)
Note:
The matrix entries must be sorted by column index.
The matrix entries within each row should be shifted to the left.
The matrix should not contain duplicate entries.
The following code snippet demonstrates how to create a 4-by-3 ell_matrix on the host with 3 nonzeros per row (6 total nonzeros) and then copies the matrix to the device.
  #include <cusp/ell_matrix.h>
  ...
  // allocate storage for (4,3) matrix with 6 nonzeros and at most 3 nonzeros per row.
  cusp::ell_matrix<int,float,cusp::host_memory> A(4,3,6,3);
  // X is used to fill unused entries in the matrix
  const int X = cusp::ell_matrix<int,float,cusp::host_memory>::invalid_index;
  // initialize matrix entries on host
  A.column_indices(0,0) = 0; A.values(0,0) = 10;
  A.column_indices(0,1) = 2; A.values(0,1) = 20;  // shifted to leftmost position
  A.column_indices(0,2) = X; A.values(0,2) =  0;  // padding
  A.column_indices(1,0) = X; A.values(1,0) =  0;  // padding
  A.column_indices(1,1) = X; A.values(1,1) =  0;  // padding
  A.column_indices(1,2) = X; A.values(1,2) =  0;  // padding
  A.column_indices(2,0) = 2; A.values(2,0) = 30;  // shifted to leftmost position
  A.column_indices(2,1) = X; A.values(2,1) =  0;  // padding
  A.column_indices(2,2) = X; A.values(2,2) =  0;  // padding
  A.column_indices(3,0) = 0; A.values(3,0) = 40;
  A.column_indices(3,1) = 1; A.values(3,1) = 50;
  A.column_indices(3,2) = 2; A.values(3,2) = 60;
  // A now represents the following matrix
  //    [10  0 20]
  //    [ 0  0  0]
  //    [ 0  0 30]
  //    [40 50 60]
  // copy to the device
  cusp::ell_matrix<int,float,cusp::device_memory> B = A;
Member Typedef Documentation
template<typename IndexType, typename ValueType, class MemorySpace> typedef cusp::array2d<IndexType, MemorySpace, cusp::column_major> cusp::ell_matrix< IndexType, ValueType, MemorySpace >::column_indices_array_type
type of column indices array
template<typename IndexType, typename ValueType, class MemorySpace> typedef cusp::ell_matrix_view<typename column_indices_array_type::const_view, typename values_array_type::const_view, IndexType, ValueType, MemorySpace> cusp::ell_matrix< IndexType, ValueType, MemorySpace >::const_view
equivalent const_view type
template<typename IndexType, typename ValueType, class MemorySpace> typedef cusp::ell_matrix<IndexType, ValueType, MemorySpace> cusp::ell_matrix< IndexType, ValueType, MemorySpace >::container
equivalent container type
template<typename IndexType, typename ValueType, class MemorySpace> typedef cusp::array2d<ValueType, MemorySpace, cusp::column_major> cusp::ell_matrix< IndexType, ValueType, MemorySpace >::values_array_type
type of values array
template<typename IndexType, typename ValueType, class MemorySpace> typedef cusp::ell_matrix_view<typename column_indices_array_type::view, typename values_array_type::view, IndexType, ValueType, MemorySpace> cusp::ell_matrix< IndexType, ValueType, MemorySpace >::view
equivalent view type
Constructor & Destructor Documentation
template<typename IndexType, typename ValueType, class MemorySpace> cusp::ell_matrix< IndexType, ValueType, MemorySpace >::ell_matrix () [inline]
Construct an empty ell_matrix.
template<typename IndexType, typename ValueType, class MemorySpace> cusp::ell_matrix< IndexType, ValueType, MemorySpace >::ell_matrix (size_t num_rows, size_t num_cols, size_t num_entries, size_t num_entries_per_row, size_t alignment = 32) [inline]
Construct an ell_matrix with a specific shape, number of nonzero entries, and maximum number of nonzero entries per row.
Parameters:
num_rows Number of rows.
num_cols Number of columns.
num_entries Number of nonzero matrix entries.
num_entries_per_row Maximum number of nonzeros per row.
alignment Amount of padding used to align the data structure (default 32).
template<typename IndexType, typename ValueType, class MemorySpace> template<typename MatrixType > cusp::ell_matrix< IndexType, ValueType, MemorySpace >::ell_matrix (const MatrixType & matrix) [inline]
Construct an ell_matrix from another matrix.
Parameters:
matrix Another sparse or dense matrix.
Member Function Documentation
template<typename IndexType, typename ValueType, class MemorySpace> template<typename MatrixType > ell_matrix& cusp::ell_matrix< IndexType, ValueType, MemorySpace >::operator= (const MatrixType & matrix) [inline]
Assignment from another matrix.
Parameters:
matrix Another sparse or dense matrix.
template<typename IndexType, typename ValueType, class MemorySpace> void cusp::ell_matrix< IndexType, ValueType, MemorySpace >::resize (size_t num_rows, size_t num_cols, size_t num_entries, size_t num_entries_per_row, size_t alignment) [inline]
Resize matrix dimensions and underlying storage
template<typename IndexType, typename ValueType, class MemorySpace> void cusp::ell_matrix< IndexType, ValueType, MemorySpace >::resize (size_t num_rows, size_t num_cols, size_t num_entries, size_t num_entries_per_row) [inline]
Resize matrix dimensions and underlying storage
Referenced by cusp::hyb_matrix< int, ValueType, MemorySpace >::resize(), and cusp::ell_matrix< int, ValueType, MemorySpace >::resize().
template<typename IndexType, typename ValueType, class MemorySpace> void cusp::ell_matrix< IndexType, ValueType, MemorySpace >::swap (ell_matrix< IndexType, ValueType, MemorySpace > & matrix) [inline]
Swap the contents of two ell_matrix objects.
Parameters:
matrix Another ell_matrix with the same IndexType and ValueType.
Referenced by cusp::hyb_matrix< int, ValueType, MemorySpace >::swap(), and cusp::ell_matrix< int, ValueType, MemorySpace >::swap().
Member Data Documentation
template<typename IndexType, typename ValueType, class MemorySpace> column_indices_array_type cusp::ell_matrix< IndexType, ValueType, MemorySpace >::column_indices
Storage for the column indices of the ELL data structure.
Referenced by cusp::ell_matrix< int, ValueType, MemorySpace >::ell_matrix(), cusp::ell_matrix< int, ValueType, MemorySpace >::resize(), and cusp::ell_matrix< int, ValueType, MemorySpace >::swap().
template<typename IndexType, typename ValueType, class MemorySpace> const IndexType cusp::ell_matrix< IndexType, ValueType, MemorySpace >::invalid_index = static_cast<IndexType>(-1) [static]
Value used to pad the rows of the column_indices array.
template<typename IndexType, typename ValueType, class MemorySpace> values_array_type cusp::ell_matrix< IndexType, ValueType, MemorySpace >::values
Storage for the nonzero entries of the ELL data structure.
Referenced by cusp::ell_matrix< int, ValueType, MemorySpace >::ell_matrix(), cusp::ell_matrix< int, ValueType, MemorySpace >::resize(), and cusp::ell_matrix< int, ValueType, MemorySpace >::swap().
The documentation for this class was generated from the following file:
ell_matrix.h