cusp: cusp::coo_matrix< IndexType, ValueType, MemorySpace > Class Template Reference
cusp::coo_matrix< IndexType, ValueType, MemorySpace > Class Template Reference
[Sparse Matrix Containers]
#include <coo_matrix.h>
Classes
struct rebind
Public Types
typedef cusp::array1d
< IndexType, MemorySpace > row_indices_array_type
typedef cusp::array1d
< IndexType, MemorySpace > column_indices_array_type
typedef cusp::array1d
< ValueType, MemorySpace > values_array_type
typedef cusp::coo_matrix
< IndexType, ValueType,
MemorySpace > container
typedef cusp::coo_matrix_view
< typename
row_indices_array_type::view,
typename
column_indices_array_type::view,
typename
values_array_type::view,
IndexType, ValueType,
MemorySpace > view
typedef cusp::coo_matrix_view
< typename
row_indices_array_type::const_view,
typename
column_indices_array_type::const_view,
typename
values_array_type::const_view,
IndexType, ValueType,
MemorySpace > const_view
Public Member Functions
coo_matrix ()
coo_matrix (size_t num_rows, size_t num_cols, size_t num_entries)
template<typename MatrixType >
coo_matrix (const MatrixType &matrix)
void resize (size_t num_rows, size_t num_cols, size_t num_entries)
void swap (coo_matrix &matrix)
template<typename MatrixType >
coo_matrix & operator= (const MatrixType &matrix)
void sort_by_row (void)
void sort_by_row_and_column (void)
bool is_sorted_by_row (void)
bool is_sorted_by_row_and_column (void)
Public Attributes
row_indices_array_type row_indices
column_indices_array_type column_indices
values_array_type values
Detailed Description
template<typename IndexType, typename ValueType, class MemorySpace>
class cusp::coo_matrix< IndexType, ValueType, MemorySpace >
coo_matrix : Coordinate matrix container
Template Parameters:
IndexType Type used for matrix indices (e.g. int).
ValueType Type used for matrix values (e.g. float).
MemorySpace A memory space (e.g. cusp::host_memory or cusp::device_memory)
Note:
The matrix entries must be sorted by row index.
The matrix should not contain duplicate entries.
The following code snippet demonstrates how to create a 4-by-3 coo_matrix on the host with 6 nonzeros and then copies the matrix to the device.
  #include <cusp/coo_matrix.h>
  ...
  // allocate storage for (4,3) matrix with 6 nonzeros
  cusp::coo_matrix<int,float,cusp::host_memory> A(4,3,6);
  // initialize matrix entries on host
  A.row_indices[0] = 0; A.column_indices[0] = 0; A.values[0] = 10;
  A.row_indices[1] = 0; A.column_indices[1] = 2; A.values[1] = 20;
  A.row_indices[2] = 2; A.column_indices[2] = 2; A.values[2] = 30;
  A.row_indices[3] = 3; A.column_indices[3] = 0; A.values[3] = 40;
  A.row_indices[4] = 3; A.column_indices[4] = 1; A.values[4] = 50;
  A.row_indices[5] = 3; A.column_indices[5] = 2; A.values[5] = 60;
  // A now represents the following matrix
  //    [10  0 20]
  //    [ 0  0  0]
  //    [ 0  0 30]
  //    [40 50 60]
  // copy to the device
  cusp::coo_matrix<int,float,cusp::device_memory> B = A;
Member Typedef Documentation
template<typename IndexType, typename ValueType, class MemorySpace> typedef cusp::array1d<IndexType, MemorySpace> cusp::coo_matrix< IndexType, ValueType, MemorySpace >::column_indices_array_type
type of column_indices array
template<typename IndexType, typename ValueType, class MemorySpace> typedef cusp::coo_matrix_view<typename row_indices_array_type::const_view, typename column_indices_array_type::const_view, typename values_array_type::const_view, IndexType, ValueType, MemorySpace> cusp::coo_matrix< IndexType, ValueType, MemorySpace >::const_view
equivalent const_view type
template<typename IndexType, typename ValueType, class MemorySpace> typedef cusp::coo_matrix<IndexType, ValueType, MemorySpace> cusp::coo_matrix< IndexType, ValueType, MemorySpace >::container
equivalent container type
template<typename IndexType, typename ValueType, class MemorySpace> typedef cusp::array1d<IndexType, MemorySpace> cusp::coo_matrix< IndexType, ValueType, MemorySpace >::row_indices_array_type
type of row_indices array
template<typename IndexType, typename ValueType, class MemorySpace> typedef cusp::array1d<ValueType, MemorySpace> cusp::coo_matrix< IndexType, ValueType, MemorySpace >::values_array_type
type of values array
template<typename IndexType, typename ValueType, class MemorySpace> typedef cusp::coo_matrix_view<typename row_indices_array_type::view, typename column_indices_array_type::view, typename values_array_type::view, IndexType, ValueType, MemorySpace> cusp::coo_matrix< IndexType, ValueType, MemorySpace >::view
equivalent view type
Constructor & Destructor Documentation
template<typename IndexType, typename ValueType, class MemorySpace> cusp::coo_matrix< IndexType, ValueType, MemorySpace >::coo_matrix () [inline]
Construct an empty coo_matrix.
template<typename IndexType, typename ValueType, class MemorySpace> cusp::coo_matrix< IndexType, ValueType, MemorySpace >::coo_matrix (size_t num_rows, size_t num_cols, size_t num_entries) [inline]
Construct a coo_matrix with a specific shape and number of nonzero entries.
Parameters:
num_rows Number of rows.
num_cols Number of columns.
num_entries Number of nonzero matrix entries.
template<typename IndexType, typename ValueType, class MemorySpace> template<typename MatrixType > cusp::coo_matrix< IndexType, ValueType, MemorySpace >::coo_matrix (const MatrixType & matrix) [inline]
Construct a coo_matrix from another matrix.
Parameters:
matrix Another sparse or dense matrix.
Member Function Documentation
template<typename IndexType, typename ValueType, class MemorySpace> bool cusp::coo_matrix< IndexType, ValueType, MemorySpace >::is_sorted_by_row (void)
Determine whether matrix elements are sorted by row index
Returns:
false, if the row indices are unsorted; true, otherwise.
template<typename IndexType, typename ValueType, class MemorySpace> bool cusp::coo_matrix< IndexType, ValueType, MemorySpace >::is_sorted_by_row_and_column (void)
Determine whether matrix elements are sorted by row and column index
Returns:
false, if the row and column indices are unsorted; true, otherwise.
template<typename IndexType, typename ValueType, class MemorySpace> template<typename MatrixType > coo_matrix& cusp::coo_matrix< IndexType, ValueType, MemorySpace >::operator= (const MatrixType & matrix) [inline]
Assignment from another matrix.
Parameters:
matrix Another sparse or dense matrix.
template<typename IndexType, typename ValueType, class MemorySpace> void cusp::coo_matrix< IndexType, ValueType, MemorySpace >::resize (size_t num_rows, size_t num_cols, size_t num_entries) [inline]
Resize matrix dimensions and underlying storage
Referenced by cusp::hyb_matrix< int, ValueType, MemorySpace >::resize(), and cusp::coo_matrix< int, ValueType, MemorySpace >::resize().
template<typename IndexType, typename ValueType, class MemorySpace> void cusp::coo_matrix< IndexType, ValueType, MemorySpace >::sort_by_row (void)
Sort matrix elements by row index
template<typename IndexType, typename ValueType, class MemorySpace> void cusp::coo_matrix< IndexType, ValueType, MemorySpace >::sort_by_row_and_column (void)
Sort matrix elements by row and column index
template<typename IndexType, typename ValueType, class MemorySpace> void cusp::coo_matrix< IndexType, ValueType, MemorySpace >::swap (coo_matrix< IndexType, ValueType, MemorySpace > & matrix) [inline]
Swap the contents of two coo_matrix objects.
Parameters:
matrix Another coo_matrix with the same IndexType and ValueType.
Referenced by cusp::hyb_matrix< int, ValueType, MemorySpace >::swap(), and cusp::coo_matrix< int, ValueType, MemorySpace >::swap().
Member Data Documentation
template<typename IndexType, typename ValueType, class MemorySpace> column_indices_array_type cusp::coo_matrix< IndexType, ValueType, MemorySpace >::column_indices
Storage for the column indices of the COO data structure.
Referenced by cusp::coo_matrix< int, ValueType, MemorySpace >::resize(), and cusp::coo_matrix< int, ValueType, MemorySpace >::swap().
template<typename IndexType, typename ValueType, class MemorySpace> row_indices_array_type cusp::coo_matrix< IndexType, ValueType, MemorySpace >::row_indices
Storage for the row indices of the COO data structure.
Referenced by cusp::coo_matrix< int, ValueType, MemorySpace >::resize(), and cusp::coo_matrix< int, ValueType, MemorySpace >::swap().
template<typename IndexType, typename ValueType, class MemorySpace> values_array_type cusp::coo_matrix< IndexType, ValueType, MemorySpace >::values
Storage for the nonzero entries of the COO data structure.
Referenced by cusp::coo_matrix< int, ValueType, MemorySpace >::resize(), and cusp::coo_matrix< int, ValueType, MemorySpace >::swap().
The documentation for this class was generated from the following file:
coo_matrix.h