cusp: cusp::convergence_monitor< Real > Class Template Reference
cusp::convergence_monitor< Real > Class Template Reference
#include <monitor.h>
Public Member Functions
template<typename Vector >
convergence_monitor (const Vector &b, size_t iteration_limit=500, Real relative_tolerance=1e-5, Real absolute_tolerance=0)
template<typename Vector >
bool finished (const Vector &r)
void print (void)
Real immediate_rate (void)
Real geometric_rate (void)
Real average_rate (void)
Public Attributes
cusp::array1d< Real,
cusp::host_memory > residuals
Detailed Description
template<typename Real>
class cusp::convergence_monitor< Real >
convergence_monitor is similar to default monitor except that it displays the solver status during iteration and reports a summary after iteration has stopped.
Template Parameters:
Real real-valued type (e.g. float or double).
See also:
default_monitor
Member Function Documentation
template<typename Real > template<typename Vector > bool cusp::convergence_monitor< Real >::finished (const Vector & r) [inline]
applies convergence criteria to determine whether iteration is finished
Parameters:
r residual vector of the linear system (r = b - A x)
Template Parameters:
Vector vector
Reimplemented from cusp::default_monitor< Real >.
References cusp::default_monitor< Real >::converged(), cusp::default_monitor< Real >::iteration_count(), cusp::default_monitor< Real >::iteration_limit(), and cusp::convergence_monitor< Real >::residuals.
Member Data Documentation
template<typename Real > cusp::array1d<Real,cusp::host_memory> cusp::convergence_monitor< Real >::residuals
Construct a convergence_monitor for a given right-hand-side b
The convergence_monitor terminates iteration when the residual norm satisfies the condition ||b - A x|| <= absolute_tolerance + relative_tolerance * ||b|| or when the iteration limit is reached.
Parameters:
b right-hand-side of the linear system A x = b
iteration_limit maximum number of solver iterations to allow
relative_tolerance determines convergence criteria
absolute_tolerance determines convergence criteria
Template Parameters:
VectorType vector
Referenced by cusp::convergence_monitor< Real >::finished().
The documentation for this class was generated from the following file:
monitor.h